### ISSUE TITLE
Question about accessing FHIR Resource Contents (ex. MedicationStatement dose) within matching records

### ISSUE THREAD

**Issue by eric-chou** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#3]
Hello,
I work as a researcher with the University of Pittsburgh Department of Biomedical Informatics and we have been working with this authoring tool to implement a drug-drug interaction alerting system.

In some of the alerts we are trying to implement, we would like to access the contents within a [MedicationStatement](https://hl7.org/fhir/STU3/medicationstatement.html), such as "dosage", "effectiveDateTime", or the contained "[Medication](https://hl7.org/fhir/STU3/medication.html)" resource. However, currently we have only been able to figure out how to use the Expressions in the tool to return lists of MedicationStatements, or booleans for if MedicationStatements exist, are active, or are/are not null, etc (screenshots below). Are there any other expressions or other aspects of the authoring tool that can allow us to reference other items within the MedicationStatement resource other than these? 

<img width="1149" alt="Screen Shot 2019-09-23 at 2 50 21 PM" src="https://user-images.githubusercontent.com/9423731/65455460-45e7a800-de15-11e9-977b-f3984a67bd07.png">

<img width="1177" alt="Screen Shot 2019-09-23 at 2 50 45 PM" src="https://user-images.githubusercontent.com/9423731/65455575-7f201800-de15-11e9-95c1-564ee3adcb92.png">

Also, if there is a different communication channel or forum to discuss CQL features/potential future features such as this one for the authoring tool, my colleagues and I would love to be included in it. Thanks!

**Comment by cmoesel** [comment]
Hi @eric-chou!  I apologize for the late response.  It's been a week!

It's exciting to hear about your use of the CDS Authoring Tool!  I hope you've found it helpful so far. In regard to your question, there isn't currently a way to get at those lower level details (as you seem to have discovered on your own).  Since those properties are completely different from resource to resource, it's a bit more work to support something like that -- especially since we've tried to keep authoring consistent between FHIR versions as well (and property details change from version to version).  Still, this is something we can put on our backlog to consider for a future version.

Using the current authoring tool, you could export the CQL and then hand-modify the bits that the Authoring Tool doesn't support.  This requires knowledge of CQL but provides you the most flexibility to go "the last mile" to make your CDS work for you.

I'd also note that the CDS Authoring Tool is open source.  If you or your colleagues are software developers and want to try implementing some of this functionality yourselves, we'd be glad to accept a Pull Request.  Since this would be a significant feature, however, I'd suggest we discuss in more detail first to ensure we're all on the same page.

Thanks again for reaching out!

**Comment by cmoesel** [comment]
Closing this issue since it is over one year old and the questions have been answered.  If you have any other questions, please feel free to open another issue!

Thanks!
