### ISSUE TITLE
Import CQL for authoring

### ISSUE THREAD

**Issue by naingtu** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#30]
Is there a capability to import existing CQL to Artifacts rather than creating a new one from scratch? It would be nice to be able to modify the published artifacts. Thanks in advance.

**Comment by cmoesel** [comment]
Hi @naingtu -- I apologize for the late answer; we somehow missed this question when it first came in.

The CDS Authoring Tool allows authors to upload externally authored CQL to an artifact, but it is read-only: you can _use_ definitions from the uploaded CQL, but you cannot edit them.  For example, if you upload a library with a CVD Risk Calculator, you can reference a risk calculation from the library (and compare it to a certain number, for example) -- but you can't modify the calculation logic itself.  This is covered in the [External CQL](https://cds.ahrq.gov/authoring/documentation#External_CQL) section of the User Guide.

We don't support importing external CQL for editing because CQL is a very broad spec and the CDS Authoring Tool does not provide a sufficient user interface (UI) to be able to present arbitrary CQL to the user via its edit controls.  There are many CQL constructs we cannot render into our UI.
