### ISSUE TITLE
Cannot login in using default user and password.

### ISSUE THREAD

**Issue by dilvan1** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#78]
I compiled the Authoring Tool using the instructions at _Run (Development Quick Start)_. Everything went fine (with some warnings), and the tool ran, but I could not log in. I tried the pair user: _demo_ and password: _password_, and made sure I copied the `local.json` and `local-users.json` files to their proper places.

I got the message `Authentication Error: 500 Internal Server Error, please try again.` on the browser and the following messages on the console:
```
11:40:31 AM web.1 |  Proxy error: Could not proxy request /authoring/api/auth/login from localhost:5100 to http://localhost:3001.
11:40:31 AM web.1 |  See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```
By the way, the project docker is not available: 
```
Unable to find image 'cdsauthoringtool:latest' locally
docker: Error response from daemon: pull access denied for cdsauthoringtool, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

**Comment by cmoesel** [comment]
Hi @dilvan1. This sounds like the backend API server is not running correctly.  Please ensure that MongoDB 4.4 is running locally and that the backend API server (on port 3001) did not have any errors launching.  The node foreman script should launch the backend API server for you, but it won't launch MongoDB for you (and will fail if MongoDB is not running).

As for DockerHub, this project is not offered on DockerHub because there are specific environment variables and values that are built into the image -- the values of which differ depending on your environment.   So you must build the image yourself if you want to use Docker.

**Comment by dilvan1** [comment]
Hi

   It only works with MongoDB 4.4 . There is a migration functionality that
isn't supported on versions greater than 4.4. In the README.md page, it
says: The CDS Authoring Tool is tested using MongoDB 4.4.x, but later
versions are expected to work.

   Thanks,

Dilvan Moreira.

From my phone.

**Comment by dilvan1** [comment]
Hi,

   I am able to edit CQL and upload patients (from Synthea), but when I run
a test (Testing page: Execute CQL on Selected Patients ) I get:
Execution failed. Error: Cannot read properties of undefined (reading
'content')
   It seems like a JavaScript bug.
--
Dilvan de Abreu Moreira, Ph.D.     ***@***.***
http://java.icmc.usp.br
Warning: I use a spam filter, some emails sent to me CAN be lost!

**Comment by cmoesel** [comment]
Hi Dilvan.  Are you able to download your CQL from the Authoring Tool?  Knowing if you can do that successfully will help me determine if the issue is the the CQL-to-ELM translation service or something else.

**Comment by dilvan1** [comment]
Yes, I can.

From my phone.

**Comment by cmoesel** [comment]
Hi @dilvan1 - is this the same issue as reported in #80?  Are you working together?  If so, let's just track it there.

**Comment by fiona43** [comment]
Hi @cmoesel 
From my side I'm not working with @dilvan1.  :)

**Comment by cmoesel** [comment]
OK, then @dilvan1 -- I'd like to ask you the same questions that I asked @fiona43:

* Have you uploaded custom CQL using the "External CQL" tab? If so, did it reference any value sets outside of VSAC?
* Could you attach the JSON for one of your test patients to this issue? (NOTE: _Only_ do this if it is synthetic data).
* Have you tried it with a very simple CQL (e.g., one element in Inclusion criteria checking for gender or age, and one simple recommendation -- even "Hello World!")?
* What browser are you using?
* How are you running CDS Authoring Tool (Docker or not Docker)?

**Comment by cmoesel** [comment]
Hi @dilvan1. I've done some more investigation and I think I know what the problem is. The error `Cannot read properties of undefined (reading 'content')` happens when the CDS Authoring Tool API backend is not configured to use the CQL Translation Service (which translates human-readable CQL to machine-friendly ELM JSON). Execution requires the ELM JSON representation of CQL, so when it is not there, execution fails.

I suspect you probably copied the [minimal-example.json](https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool/blob/master/api/config/minimal-example.json) when you created your `local.json` configuration. The minimal example unfortunately has the CQL-to-ELM Translation Service turned _off_:
```json5
{
  "cqlToElm": {
    "active": false
  },
  // other config
}
```

You'll need to install and run a CQL Translation Service and then set that value to `true` in your config. If youre CQL Translation Service is running at a URL other than `http://localhost:8080/cql/translator`, you'll also need to set the `url` property.  See [example.json](https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool/blob/master/api/config/example.json) for a more complete configuration example.

Unfortunately, it looks like this repo's README is not very clear about the requirement for the CQL Translation Service or how to install and run it. I apologize for that. If you have Docker, then the easiest way to run it is as a Docker container like this:
```
docker run -d -p 8080:8080 --restart unless-stopped cqframework/cql-translation-service:latest
```

Otherwise, you can run it using Java by following the instructions in the [CQL to ELM Translation Service README](https://github.com/cqframework/cql-translation-service#cql-to-elm-translation-service).

**Comment by dilvan1** [comment]
Hi,

   It worked for me. Maybe you should update the README.md file Run
instructions. Remember to inform that users must use MongoDB 4.4.x.

   Thanks!
--
Dilvan de Abreu Moreira, Ph.D.     ***@***.***
http://java.icmc.usp.br
Warning: I use a spam filter, some emails sent to me CAN be lost!

**Comment by cmoesel** [comment]
Thanks for confirming! I apologize for the trouble and have taken note to improve the instructions!
