### ISSUE TITLE
Importing External CQL to use in Inclusions/Subpopulations/etc

### ISSUE THREAD

**Issue by eric-chou** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#9]
Hello,
I have been trying to figure out how to use the "External CQL" part of the authoring tool (screenshot below) and have been able to get a couple CQL libraries to be successfully uploaded as a test. 

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/9423731/74060537-34fc9500-49b8-11ea-909c-5e4cbc788490.png">

I can see that the functions appear to appropriately be defined from the imported CQL...

<img width="985" alt="image" src="https://user-images.githubusercontent.com/9423731/74060661-73924f80-49b8-11ea-9ea9-16fa1bd16bcf.png">

However, it doesn't appear that any of these are usable when trying to refer to them in the Base Elements, Subpopulations, Inclusions/Exclusions.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/9423731/74060750-9fadd080-49b8-11ea-9cc1-8364acca5720.png">

Do you have any insight as to what else might need to be done or anything I might be missing in order to be able to refer to the functions defined in the external CQL? Are there any example use cases of this with functional CQL snippets that I can try to go off of? I haven't been able to find documentation for using this portion of the authoring tool.

Thank you!

**Comment by cmoesel** [comment]
Hi @eric-chou.  Currently, the "External CQL" feature can only be used to reference definitions and parameters -- _not_ functions.  So the reason you do not see them listed where you invoke external CQL is that they are not supported.

I apologize that the documentation is not very clear about this.  [It's actually quite subtle](https://cds.ahrq.gov/authoring/documentation#External_CQL):
> Once an external CQL file has been uploaded, any of its definitions or parameters can be used within Inclusions, Exclusions, Subpopulations, or Base Elements.

We should probably update the documentation to explicitly state that `function`s are not supported.

So... if your External CQL has something like:
```
define MyObservations: [Observation: "My ValueSet"]
```
-- that can be used.  But if it is a function, it cannot be.

Since functions can take in arbitrary arguments (and an arbitrary number of arguments), adding support to directly invoke external functions will likely require designing some new approaches to the element builder.  While this is something we'd like to eventually support, we don't currently have immediate plans to support it.

**Comment by eric-chou** [comment]
Ok that makes sense, thanks!
